### ISSUE TITLE
help pyro get ansible going.

### ISSUE THREAD

**Issue by bearsears** [bearsears/docker_SIEM#5]

**Comment by pyrovatra** [comment]
![UnicornPee](https://github.com/bearsears/docker_SIEM/assets/61298375/a8088180-c2d4-4f4b-8a4f-029149d7bd8a)

**Comment by bearsears** [comment]
hey unicorn,
- git clone main, 
- make sure to know the address of the vm, 
- add your user in vm as a sudoer, so you don't get blocked while running ansible,
- change the ip in the vm_inventory.yml, as well as user,
- try running,  ansible-playbook -i vm_inventory.ini start_docker.yml
