### ISSUE TITLE
create new ansible task for creating new folder

### ISSUE THREAD

**Issue by pyrovatra** [bearsears/docker_SIEM#6]

**Comment by bearsears** [comment]
let's both do this, and branch out to milan and steven, and by sunday, push our solution to git, and compare,

**Comment by bearsears** [comment]
branched out to steven, and added a task called "install a folder..." into the playbook, and pushed to the git.

**Comment by pyrovatra** [comment]
branched out to dface, added a task "create a new folder" into the playbook and edited into git

**Comment by bearsears** [comment]
closing
